config/routes.rb
Rails.application.routes.draw do
  resources :label

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    member do
      delete :delete_file_attachment
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups

  namespace :admin do
    resources :users
  end

  resources :groupings, only: [:create, :destroy]

  get '/calendar', to: 'tasks#calendar'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  include AASM

  aasm :column => 'status' do
    state :waiting, :initial => true
    state :doing, :done

    event :run do
      transitions :from => :waiting, :to => :doing
    end

    event :finish do
      transitions :from => :doing, :to => :done
    end
  end

  validates :name, presence: true
  validates :detail, presence: true

  enum priority: ['低', '中', '高']

  has_many :labelings, dependent: :destroy, foreign_key: 'task_id'
  has_many :labels, through: :labelings, source: :label
  accepts_nested_attributes_for :labelings

  has_many :reads, dependent: :destroy

  has_many_attached :files
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  before_action :sign_in_user

  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result.order(created_at: :desc)
    @tasks = @tasks.page(params[:page]).per(10).where(user: current_user)
  end

  def new
    if params[:back]
      @task = Task.new(task_params)
    else
      @task = Task.new
      @task.labelings.build
    end
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました!"
    else
      render 'new'
    end
  end

  def show
    if @task.reads.find_by(user_id: current_user.id).nil?
      @task.reads.create(user_id: current_user.id, flg: true, task_id: @task.id)
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました！"
  end

  def confirm
    @task = Task.new(task_params)
    render :new if @task.invalid?
  end

  def delete_file_attachment
    @file = ActiveStorage::Attachment.find(params[:id])
    @file.purge
    redirect_back(fallback_location: request.referer)
  end

  def calendar
    @tasks = Task.where(user: current_user)
  end

  private

  def task_params
    params.require(:task).permit(:name, :detail, :endtime, :status, :priority, :user_id, :read, label_ids: [], files: [])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def sign_in_user
    redirect_to new_session_path unless logged_in?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def time_alert
    expire_date = Time.zone.today + 3
    @expirations = Task.all.where(user_id: current_user.id).where("endtime <= ?", expire_date).where.not(status: :done)
    return @expirations if @expirations.present?
  end
end

app/views/tasks/_form.html.erb
<div class="form-group">
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> が存在しているため保存出来ません:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :endtime %>
    <%= form.date_field :endtime, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, [["未着手", "waiting"], ["着手中", "doing"],  ["完了", "done"]],{}, {class: "form-control"}  %>
  </div>

  <% if @task.files.attached? %>
  <div class="field">
    <label>ファイル一覧</label>
    <br>
    <% @task.files.each do |file| %>
      <%= link_to file.filename, file, target: '_blank' %>
      <font size="-1">
       <%= link_to '削除する', delete_file_attachment_task_url(file.id), method: :delete, data: { confirm: '削除しますか?' } %>
      </font>
      <br>
    <% end %>
  </div>
  <% end %>


  <div class="field">
    <%= form.label "ファイル添付" %>
    <%= form.file_field :files, multiple: true, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys.to_a,{}, {class: "form-control"} %>
  </div>
<br>
<%= t('view.label') %>
<br>
<% label_list.each do |label| %>
  <% if action_name == "new" || action_name == "create" %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id] %>
    <label style="background-color: lightblue"><%= label.name %></label>
  <% elsif action_name == "edit" || action_name == "update" %>
    <%= form.check_box :label_ids, { multiple: true, checked: @task.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false}, label[:id] %>
    <label style="background-color: lightblue"><%= label.name %></label>
  <% end %>
<% end %>
<br>
<%= link_to '新しくラベルを作成', new_label_path, class: "btn btn-outline-dark btn-sm"  %>
<br>
<hr>
<br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/tasks/calendar.html.erb
<%= month_calendar events: @tasks, attribute: :endtime do |date, tasks| %>
  <%= date.to_formatted_s(:only_day) %>

  <% tasks.each do |task| %>
    <div>
      <font color="red" size="-1">期限タスク: <%= link_to task.name, task %></font>
    </div>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h4><%= t('view.task') %><%= t('view.edit') %></h4>

<%= render 'form', task: @task %>


<%= link_to '詳細', @task, class: "btn btn-outline-dark btn-sm" %>
<%= link_to '戻る', tasks_path, class: "btn btn-outline-dark btn-sm" %>

app/views/tasks/index.html.erb
<% if time_alert %>
  <div class="alert alert-danger" role="alert"">
    <%= @expirations.count %> 件の期限切れ、または期限間近のタスクがあります。
    <ul>
    <% @expirations.each do |expiration| %>
      <li><%= link_to expiration.name, expiration %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class="nav-scroller bg-white box-shadow">
    <nav class="nav nav-underline">

        <%= search_form_for @q do |f| %>

          <%= f.label :name_cont, "タスク名検索" %>
          <%= f.search_field :name_cont %>
          <%= f.label :status_eq, "ステータス検索" %>
          <%= f.select :status_eq, [["未着手", "waiting"], ["着手中", "doing"], ["完了", "done"]], include_blank: true %>
          <%= f.label :labels_id_eq, "ラベル検索" %>
          <%= f.collection_select :labels_id_eq, label_list, :id, :name, include_blank: true %>
          <%= f.submit "検索" %>
        <% end %>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to '検索条件のクリア', request.path %>
          </li>
        </ul>
    </nav>
</div>


<hr>

<h4><%= t('view.task') %><%= t('view.index') %></h4>
<div style="text-align: right">
<%= link_to 'タスク新規作成', new_task_path, class: "btn btn-dark btn-sm"  %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('view.unread') %></th>
      <th><%= t('view.username') %></th>
      <th><%= t('view.taskname') %></th>
      <th><%= sort_link(@q, :endtime, t('view.endtime'), default_order: :desc) %></th>
      <th><%= t('view.status') %></th>
      <th><%= sort_link(@q, :priority, t('view.priority'), default_order: :desc) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <%= render 'layouts/task_list' %>
</table>

<%= paginate @tasks %>

<br>
<br>

app/views/tasks/new.html.erb
<h4><%= t('view.task') %><%= t('view.create') %></h4>

<%= render 'form', task: @task, class: "btn btn-outline-dark btn-sm"  %>

<%= link_to '戻る', tasks_path, class: "btn btn-outline-dark btn-sm"  %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
<tr>
<th>
  <%= t('view.taskname') %>
  </th>
  <td>
  <%= @task.name %>
</td>
</tr>
<tr>
<th>
  <%= t('view.taskdetail') %>
</th>
<td>
  <%= @task.detail %>
</td>
</tr>
<tr>
<th>
  <%= t('view.endtime') %>
</th>
<td>
  <%= @task.endtime %>
</td>
</tr>
<tr>
<th>
  <%= t('view.status') %>
</th>
<td>
  <%= @task.aasm.human_state %>
</td>
</tr>
<tr>
<th>
  <%= t('view.priority') %>
</th>
<td>
  <%= @task.priority %>
</td>
</tr>
<tr>
<th>
  <%= t('view.label') %>
</th>
<td>
  <% @task.label_ids.each do |label| %>
  <label style="background-color:lightblue"><%= Label.find(label).name %></label>
  <% end %>
</td>
</tr>
<tr>
<th>
  <%= t('view.files') %>
</th>
<td>
  <% if @task.files.attached? %>
    <% @task.files.each do |file| %>
      <%= link_to file.filename, file, target: '_blank' %>
      <br>
    <% end %>
  <% end %>
</td>
</tr>
</table>
<%= link_to '編集', edit_task_path(@task), class: "btn btn-outline-dark btn-sm"  %>
<%= link_to '戻る', :back, class: "btn btn-outline-dark btn-sm"  %>