config/routes.rb
Rails.application.routes.draw do
  resources :label

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    member do
      delete :delete_file_attachment
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups

  namespace :admin do
    resources :users
  end

  resources :groupings, only: [:create, :destroy]

  get '/calendar', to: 'tasks#calendar'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :groupings, dependent: :destroy
  has_many :group_users, through: :groupings, source: :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :edit_group, only: [:edit, :update, :destroy]
  before_action :sign_in_user
  before_action :user_in_group, only: [:show]

  def index
    @groups = Group.all
    @grouping = current_user.groupings.find_by(user_id: current_user.id)
  end

  def new
    if params[:back]
      @group = Group.new(group_params)
    else
      @group = Group.new
      @group.groupings.build
    end
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.groupings.build(user_id: current_user.id, group_id: @group.id)
    if @group.save
      redirect_to groups_path, notice: "グループを作成しました!"
    else
      render 'new'
    end
  end

  def show
    groupusers = @group.group_users.ids
    @tasks = Task.where(:user_id => groupusers)
    @tasks = @tasks.page(params[:page]).per(10)
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: "グループを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: "グループを削除しました！"
  end

  def confirm
    @group = Group.new(group_params)
    render :new if @group.invalid?
  end

  private

  def group_params
    params.require(:group).permit(:name, :info, :owner_id, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def edit_group
    if @group.owner_id != current_user.id
      redirect_to groups_path, notice: 'グループの編集は作成者のみが行えます'
    end
  end

  def sign_in_user
    redirect_to new_session_path unless logged_in?
  end

  def user_in_group
    unless @group.group_users.ids.include?(current_user.id)
      redirect_to groups_path, notice: '詳細画面はグループメンバーのみ参照できます'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="form-group">
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> が存在しているため保存出来ません:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info, class: "form-control"  %>
  </div>

<br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/groups/edit.html.erb
<h4><%= t('view.group') %><%= t('view.edit') %></h4>

<%= render 'form', group: @group %>

<%= link_to '詳細', @group, class: "btn btn-outline-dark btn-sm" %>
<%= link_to '戻る', groups_path, class: "btn btn-outline-dark btn-sm" %>

app/views/groups/index.html.erb
<h4><%= t('view.group') %><%= t('view.index') %></h4>
<div style="text-align: right">
<%= link_to 'グループ新規作成', new_group_path, class: "btn btn-dark btn-sm"  %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('view.groupname') %></th>
      <th><%= t('view.groupinfo') %></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.info %></td>
        <td>
      <% if group.owner_id == current_user.id %>
        </td>
      <% else %>
        <% if group.group_users.find_by(id: current_user.id) %>
          <%= link_to 'グループから抜ける', grouping_path(id: @grouping.id), method: :delete, data: { confirm: 'グループから抜けますか?' }, class: 'btn btn-outline-danger btn-sm' %>
        <% else %>
          <%= link_to 'グループに参加する', groupings_path(group_id: group.id), method: :post, data: { confirm: 'グループに参加しますか?' }, class: 'btn btn-outline-secondary btn-sm' %>
        <% end %>
        </td>
      <% end %>
      <% if group.group_users.ids.include?(current_user.id) %>
        <td>
          <%= link_to '詳細', group %>
        </td>
      <% else %>
        <td></td>
      <% end %>
      <% if group.owner_id == current_user.id %>
        <td>
          <%= link_to '編集', edit_group_path(group) %>
        </td>
        <td>
          <%= link_to '削除', group, method: :delete, data: { confirm: 'グループを削除しますか?' } %>
        </td>
      <% else %>
        <td colspan="2" >
        </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h4><%= t('view.group') %><%= t('view.create') %></h4>

<%= render 'form', group: @group, class: "btn btn-outline-dark btn-sm"  %>

<%= link_to '戻る', groups_path, class: "btn btn-outline-dark btn-sm"  %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
    <th>
      <%= t('view.groupname') %>
    </th>
    <td>
      <%= @group.name %>
    </td>
  </tr>
  <tr>
    <th>
      <%= t('view.groupinfo') %>
    </th>
    <td>
      <%= @group.info %>
    </td>
  </tr>
  <tr>
    <th>
      <%= t('view.user') %><%= t('view.index') %>
    </th>
    <td>
      <% @group.group_users.map(&:name).each do |name| %>
        <%= name %>
      <% end %>
    </td>
  </tr>
</table>
<%= link_to '編集', edit_group_path(@group), class: "btn btn-outline-dark btn-sm"  %>
<%= link_to '戻る', groups_path, class: "btn btn-outline-dark btn-sm"  %>

<br>
<hr>
<br>

<h5><%= @group.name %><%= t('view.task') %><%= t('view.index') %></h5>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('view.unread') %></th>
      <th><%= t('view.username') %></th>
      <th><%= t('view.taskname') %></th>
      <th><%= t('view.taskdetail') %></th>
      <th><%= t('view.endtime') %></th>
      <th><%= t('view.status') %></th>
      <th><%= t('view.priority') %></th>
    </tr>
  </thead>

    <%= render 'layouts/task_list' %>
</table>

<%= paginate @tasks %>