config/routes.rb
Rails.application.routes.draw do
  resources :label

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    member do
      delete :delete_file_attachment
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups

  namespace :admin do
    resources :users
  end

  resources :groupings, only: [:create, :destroy]

  get '/calendar', to: 'tasks#calendar'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy, foreign_key: 'label_id'
  has_many :tasks, through: :labelings, source: :label

  belongs_to :user, optional: true
end

app/controllers/label_controller.rb
class LabelController < ApplicationController
  before_action :set_label, only: [:edit, :update, :destroy]

  def new
    @label = Label.new
  end

  def index
    @labels = Label.where(user_id: current_user.id)
    @labelings = Labeling.joins(:label).where(labels: { user_id: nil }).group(:name).count
  end

  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id
    if @label.save
      redirect_to tasks_path, notice: "ラベルを作成しました!"
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @label.update(label_params)
      redirect_to label_index_path, notice: "ラベルを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @label.destroy
    redirect_to label_index_path, notice: "ラベルを削除しました！"
  end

  private

  def label_params
    params.require(:label).permit(:name, :user_id)
  end

  def set_label
    @label = Label.find(params[:id])
  end
end

app/helpers/label_helper.rb
module LabelHelper
  def label_list
    Label.all.where(user_id: nil).or(Label.all.where(user_id: current_user.id))
  end
end

app/views/label/_form.html.erb
<div class="form-group">
<%= form_with(model: @label, url: label_index_path, local: true) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/label/edit.html.erb
<h4><%= t('view.label') %>編集</h4>

<div class="form-group">
<%= form_with(model: @label, url: label_path, local: true) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

<%= link_to '戻る', :back, class: "btn btn-outline-dark btn-sm"  %>

app/views/label/index.html.erb
<h4>作成<%= t('view.label') %><%= t('view.index') %></h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('view.label') %></th>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td>
          <%= link_to '編集', edit_label_path(label) %>
        </td>
        <td>
          <%= link_to '削除', label, method: :delete, data: { confirm: 'ラベルを削除しますか?' } %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>

<p class="makespace">&nbsp;</p>

<h4>デフォルト<%= t('view.label') %><%= t('view.frequency') %></h4>
<%= column_chart @labelings %>

app/views/label/new.html.erb
<h4>新規<%= t('view.label') %>作成</h4>


<div class="form-group">
<%= form_with(model: @label, url: label_index_path, local: true) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

<%= link_to '戻る', new_task_path, class: "btn btn-outline-dark btn-sm"  %>