config/routes.rb
Rails.application.routes.draw do
  resources :label

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    member do
      delete :delete_file_attachment
    end
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :groups

  namespace :admin do
    resources :users
  end

  resources :groupings, only: [:create, :destroy]

  get '/calendar', to: 'tasks#calendar'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_task_list.html.erb
<tbody>
  <% @tasks.each do |task| %>
    <% if task.reads.find_by(user_id: current_user.id, flg: true) %>
      <tr>
        <td></td>
    <% else %>
      <tr class="readsign">
        <td>未</td>
    <% end %>
      <td><%= task.user.name %></td>
      <td><%= task.detail %></td>
      <td><%= task.endtime %></td>
      <td><%= task.aasm.human_state %></td>
      <td><%= task.priority  %></td>
      <td><%= link_to '詳細', task %></td>
      <td><%= link_to '編集', edit_task_path(task) %></td>
      <td><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>

app/views/layouts/_user_image.html.erb
<% if @user.image? %>
  <%= image_tag @user.image.url %>
<% else %>
  <%= image_tag("animal_arupaka.png") %>
<% end %>

<p class="makespace">&nbsp;</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
      <%= link_to 'タスク管理ツール', root_path, id: "logo", class: "navbar-brand mr-auto" %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to '管理画面', admin_users_path, class: "nav-item" %>
        &nbsp;
        &nbsp;
      <% end %>
      <% if logged_in? %>
          <%= link_to current_user.name, user_path(current_user.id), class: "nav-item" %>
          &nbsp;
          &nbsp;
          <%= link_to t('view.task'), tasks_path, class: "nav-item" %>
          &nbsp;
          &nbsp;
          <%= link_to t('view.calendar'), calendar_path, class: "nav-item" %>
          &nbsp;
          &nbsp;
          <%= link_to t('view.group'), groups_path, class: "nav-item" %>
          &nbsp;
          &nbsp;
          <%= link_to t('view.label'), label_index_path, class: "nav-item" %>
          &nbsp;
          &nbsp;
          <%= link_to t('view.logout'), session_path(current_user.id), method: :delete, class: "nav-item" %>
      <% end %>
    </nav>

  <div class="container">

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <br>
    <% end %>

        <%= yield %>
 </div>



  </body>
</html>